sudo: required
language: node_js
dist: trusty

os:
  - osx

osx_image: "xcode8.3"

node_js:
  - "7"

cache:
  directories:
    - node_modules

install:
- sudo spctl --master-disable
- npm install
- npm run postinstall

before_script:
- npm run pretest

script:
- npm run lint
- npm run build:osx

