# appveyor file
# http://www.appveyor.com/docs/appveyor-yml

# Test against this version of Node.js
os: unstable

cache:
  - node_modules -> package.json
  - static/node_modules -> static/package.json

environment:
  matrix:
    - nodejs_version: '7'

matrix:
  fast_finish: true

platform:
  - x64

branches:
  only:
    - master

# Install scripts. (runs after repo cloning)
install:
  - ps: Install-Product node $env:nodejs_version
  - set CI=true
  - npm -g install npm@latest
  - set PATH=%APPDATA%\npm;%PATH%
  - npm install
  - npm run postinstall

# Post-install test scripts.
test_script:
  - node --version
  - npm --version
  - npm run pretest
  - npm run lint
  - npm run build:win
  - npm run publish:bos
  - npm run publish:github

# Don't actually build.
build: off
version: "{build}"
shallow_clone: true
clone_depth: 1
